name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_EMAIL }}" --password-stdin
      
      - name: Build Docker image
        run: docker build -t emartbackend/e-com ..
      
      - name: Publish image to Docker Hub
        run: docker push emartbackend/e-com:latest

  deploy:
    needs: build
    runs-on: self-hosted  # Ensure your self-hosted runner is properly set up
    steps:
      - name: Pull image from Docker Hub
        run: docker pull emartbackend/e-com:latest
      
      - name: Delete old container
        run: docker rm -f e-com-container || true  # Avoid failure if the container does not exist
      
      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name e-com-container emartbackend/e-com:latest
